_NAME := $(notdir $(CURDIR))
_DATE := $(shell date +%Y-%m-%d-%H-%M-%S)


# run: 
# 	# docker build  --platform linux/amd64  -t $(_NAME) . 



build: 
	./scripts/build.sh
	# docker build  --platform linux/amd64  -t $(_NAME) . 
